<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'id' => '9738edab-e647-41b4-8c88-f586591a32d7',
                'sku' => 'SKU-FREUDIAN-DC',
                'name' => 'Freudian Daniel Caesar',
                'brand' => 'Daniel Caesar',
                'description' => 'Album Freudian - Daniel Caesar. Dirilis secara independen pada 25 Agustus 2017, album ini menyuguhkan gabungan antara R&B, soul, dan gospel dengan lirik yang mendalam tentang cinta, pengampunan, dan spiritualitas.',
                'price' => 690000,
                'image' => 'nooisefoto/freudian.jpg',
                'tracklist' => json_encode([
                    "Get You (feat. Kali Uchis)",
                    "Best Part (feat. H.E.R.)",
                    "Hold Me Down",
                    "Neu Roses (Transgressor's Song)",
                    "Loose",
                    "We Find Love",
                    "Blessed",
                    "Take Me Away (feat. Syd)",
                    "Transform (feat. Charlotte Day Wilson)",
                    "Freudian"
                ]),
                'color' => 'brown',
                'vinyl_class' => '',
                'category' => 'rnb',
            ],
            [
                'id' => 'f5b91dfb-17c6-463a-86c0-9e2f8b49279f',
                'sku' => 'SKU-BABY-JB',
                'name' => 'Baby Justin Bieber',
                'brand' => 'Justin Bieber',
                'description' => 'Album Baby - Justin Bieber. Lagu pop legendaris yang merajai tangga lagu dunia, dirilis sebagai bagian dari album debut legendarisnya My World 2.0.',
                'price' => 550000,
                'image' => 'nooisefoto/Justin Bieber _ My World 2_0 _ Album art, Promo photos.jpg',
                'tracklist' => json_encode([
                    "Baby (feat. Ludacris)",
                    "Somebody to Love",
                    "Stuck in the Moment",
                    "U Smile",
                    "Runaway Love",
                    "Never Let You Go",
                    "Overboard (feat. Jessica Jarrell)",
                    "Up",
                    "That Should Be Me"
                ]),
                'color' => 'brown',
                'vinyl_class' => '',
                'category' => 'pop',
            ],
            [
                'id' => '59a639a7-2c90-437e-8bfb-37585dbd826c',
                'sku' => 'SKU-SOS-SZA',
                'name' => 'SOS SZA',
                'brand' => 'SZA',
                'description' => 'Album SOS - SZA. Karya masterpiece R&B modern yang mengeksplorasi patah hati, kecemasan diri, cinta toxic, dan pertumbuhan spiritual.',
                'price' => 690000,
                'image' => 'nooisefoto/sos.jpg',
                'tracklist' => json_encode([
                    "SOS",
                    "Kill Bill",
                    "Seek & Destroy",
                    "Low",
                    "Love Language",
                    "Blind",
                    "Shirt",
                    "Too Late",
                    "Snooze",
                    "Ghost in the Machine (feat. Phoebe Bridgers)",
                    "F2F",
                    "Nobody Gets Me",
                    "Conceited",
                    "Special",
                    "Open Arms (feat. Travis Scott)",
                    "I Hate U",
                    "Good Days"
                ]),
                'color' => 'brown',
                'vinyl_class' => '',
                'category' => 'rnb',
            ],
            [
                'id' => '42a73823-4307-4c9f-a0f3-7c08841019cd',
                'sku' => 'SKU-KEANE',
                'name' => 'Somewhere Only We Know Keane',
                'brand' => 'Keane',
                'description' => 'Album Somewhere Only We Know - Keane. Kombinasi piano-pop yang melankolis dan vokal yang memikat dalam album debut legendaris Hopes and Fears.',
                'price' => 500000,
                'image' => 'nooisefoto/Keane.jpg',
                'tracklist' => json_encode([
                    "Somewhere Only We Know",
                    "This Is the Last Time",
                    "Bend and Break",
                    "Bedshaped",
                    "Everybody's Changing",
                    "Spiralling",
                    "Silenced by the Night",
                    "Sovereign Light Café",
                    "Disconnected"
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-white',
                'category' => 'pop',
            ],
            [
                'id' => '43b79ad9-5d15-4c4f-9a22-f236c061cfc1',
                'sku' => 'SKU-NEVER-ENOUGH-DC',
                'name' => 'Never Enough Daniel Caesar',
                'brand' => 'Daniel Caesar',
                'description' => 'Album Never Enough - Daniel Caesar. Menghadirkan vokal R&B yang sangat tenang, intim, dan personal dengan perpaduan instrumen organik yang memukau.',
                'price' => 690000,
                'image' => 'nooisefoto/danielcesar.jpg',
                'tracklist' => json_encode([
                    "Ocho Rios",
                    "Valentina",
                    "Toronto 2014",
                    "Buyer's Remorse (feat. Omar Apollo)",
                    "Do You Like Me?",
                    "Always",
                    "Superpowers",
                    "Unstoppable",
                    "Pain Is Inevitable",
                    "Homage"
                ]),
                'color' => 'brown',
                'vinyl_class' => '',
                'category' => 'rnb',
            ],
            [
                'id' => 'aebf6ab8-4540-4488-b7b4-12a009cbea49',
                'sku' => 'SKU-BLOND-FO',
                'name' => 'Blond Frank Ocean',
                'brand' => 'Frank Ocean',
                'description' => 'Album Blond - Frank Ocean. Salah satu album R&B eksperimental paling diakui secara kritis di abad ke-21. Menggabungkan melodi avant-garde dengan penulisan lagu yang puitis.',
                'price' => 690000,
                'image' => 'https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg',
                'tracklist' => json_encode([
                    "Nikes",
                    "Ivy",
                    "Pink + White",
                    "Be Yourself",
                    "Solo",
                    "Self Control",
                    "Good Guy",
                    "Nights",
                    "Solo (Reprise)",
                    "Pretty Sweet",
                    "Facebook Story",
                    "Close to You",
                    "White Ferrari",
                    "Seigfried",
                    "Godspeed",
                    "Futura Free"
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-white',
                'category' => 'rnb',
            ],
            [
                'id' => 'f1f0aec6-fed7-4eb2-87a8-0019d51729eb',
                'sku' => 'SKU-CASE-STUDY-01-DC',
                'name' => 'Case Study 01 Daniel Caesar',
                'brand' => 'Daniel Caesar',
                'description' => 'Album Case Study 01 - Daniel Caesar. Penjelajahan mendalam tentang cinta, hasrat, seksuality, dan keraguan eksistensial dengan harmoni neo-soul yang kaya.',
                'price' => 600000,
                'image' => 'nooisefoto/cast.jpg',
                'tracklist' => json_encode([
                    "Entropy",
                    "Cyanide",
                    "Love Again (with Brandy)",
                    "Frontal Lobe Muzik (feat. Pharrell Williams)",
                    "Open Up",
                    "Restore the Feeling (feat. Sean Leon)",
                    "Superposition (feat. John Mayer)",
                    "Too Deep to Turn Back",
                    "Complexities",
                    "Are You OK?"
                ]),
                'color' => 'brown',
                'vinyl_class' => '',
                'category' => 'rnb',
            ],
            [
                'id' => '66bafcb1-401f-4d0c-9478-98e51476e08c',
                'sku' => 'SKU-PARTY-NEXT-DOOR-TWO',
                'name' => 'Party Next Door Two',
                'brand' => 'PartyNextDoor',
                'description' => 'Album Party Next Door Two. Karya R&B gelap nan sensual khas Toronto yang diproduseri oleh Noah \'40\' Shebib dan Drake.',
                'price' => 550000,
                'image' => 'nooisefoto/Partynextdoor Two (Vinyl).jpg',
                'tracklist' => json_encode([
                    "East Liberty",
                    "Slay (feat. Travis Scott)",
                    "Sex on the Beach",
                    "Her Way",
                    "Belong to the City",
                    "Grown Woman",
                    "Options",
                    "Thirsty",
                    "Bout It",
                    "Recognize (feat. Drake)",
                    "FWU",
                    "Muse"
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-white',
                'category' => 'rnb',
            ],
            [
                'id' => '846a73b1-9050-43e5-b84f-a3532884d3ba',
                'sku' => 'SKU-MORE-LIFE-DR',
                'name' => 'More Life Drake',
                'brand' => 'Drake',
                'description' => 'Album More Life - Drake. Sebuah playlist kompilasi genre campuran yang menyatukan hip-hop, R&B, dancehall, grime, dan afrobeat.',
                'price' => 500000,
                'image' => 'nooisefoto/Drake More Life.jpg',
                'tracklist' => json_encode([
                    "Free Smoke",
                    "No Long Talk",
                    "Passionfruit",
                    "Jorja Interlude",
                    "Get It Together",
                    "Madiba Riddim",
                    "Blem",
                    "4422",
                    "Glow (feat. Kanye West)",
                    "Since Way Back",
                    "Fake Love",
                    "KMT",
                    "Ice Melts",
                    "Do Not Disturb"
                ]),
                'color' => 'brown',
                'vinyl_class' => '',
                'category' => 'hiphop',
            ],
            [
                'id' => 'e776fb36-b8ee-41e3-b512-42b098618ed1',
                'sku' => 'SKU-HEROES-VILLAINS',
                'name' => 'Heroes Villains Metro Boomin',
                'brand' => 'Metro Boomin',
                'description' => 'Album Heroes & Villains - Metro Boomin. Produksi trap sinematik kelas dunia dengan kolaborasi bertabur bintang dari Future, Travis Scott, 21 Savage, dan Young Thug.',
                'price' => 500000,
                'image' => 'nooisefoto/Umbrella (with 21 Savage & Young Nudy).jpg',
                'tracklist' => json_encode([
                    "On Time (with John Legend)",
                    "Superhero (Heroes & Villains)",
                    "Too Many Nights (feat. Don Toliver)",
                    "Raindrops (Insane)",
                    "Umbrella",
                    "Trance (with Travis Scott & Young Thug)",
                    "Creepin' (with The Weeknd & 21 Savage)",
                    "Niagara Falls (Footprints)"
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-white',
                'category' => 'hiphop',
            ],
            [
                'id' => '3f85d71f-a2f7-4d06-a9e9-d5db5a23ec8d',
                'sku' => 'SKU-FUTURE',
                'name' => 'Future',
                'brand' => 'Future',
                'description' => 'Album Future. Karya self-titled penuh energi trap keras dengan anthem ikonik \'Mask Off\' yang mendefinisikan musik hip-hop modern.',
                'price' => 450000,
                'image' => 'nooisefoto/i am music.jpg',
                'tracklist' => json_encode([
                    "Rent Due",
                    "Draco",
                    "Mask Off",
                    "Rent Money",
                    "Super Trapper",
                    "Zoom",
                    "Extra Luv (feat. YG)",
                    "Poppin' Tags",
                    "Scrape"
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-white',
                'category' => 'hiphop',
            ],
            [
                'id' => '51efa250-568f-446d-8b38-1e9b303c6c8f',
                'sku' => 'SKU-GKMC',
                'name' => 'Good Kid MAAD City Kendrick Lamar',
                'brand' => 'Kendrick Lamar',
                'description' => 'Album Good Kid, M.A.A.D. City - Kendrick Lamar. Album konseptual legendaris yang menceritakan kehidupan keras masa muda Kendrick di kota Compton, dikemas dengan lirik puitis yang jenius.',
                'price' => 750000,
                'image' => 'nooisefoto/goodkid.jpg',
                'tracklist' => json_encode([
                    "Sherane a.k.a Master Splinter's Daughter",
                    "Bitch, Don't Kill My Vibe",
                    "Backseat Freestyle",
                    "The Art of Peer Pressure",
                    "Money Trees (feat. Jay Rock)",
                    "Poetic Justice (feat. Drake)",
                    "good kid",
                    "m.A.A.d city (feat. MC Eiht)",
                    "Swimming Pools (Drank)",
                    "Real (feat. Anna Wise)",
                    "Compton (feat. Dr. Dre)"
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-blue',
                'category' => 'hiphop',
            ],
            [
                'id' => '01e450c5-91fc-4649-9c02-4755d642f90b',
                'sku' => 'SKU-DAMN',
                'name' => 'DAMN Kendrick Lamar',
                'brand' => 'Kendrick Lamar',
                'description' => 'Album DAMN - Kendrick Lamar. Pemenang Penghargaan Pulitzer Musik pertama untuk genre non-klasik/non-jazz. Menampilkan kritik sosial yang tajam dan ketukan rap yang menggelegar.',
                'price' => 850000,
                'image' => 'https://upload.wikimedia.org/wikipedia/en/5/51/Kendrick_Lamar_-_Damn.png',
                'tracklist' => json_encode([
                    "BLOOD.",
                    "DNA.",
                    "YAH.",
                    "ELEMENT.",
                    "FEEL.",
                    "LOYALTY. (feat. Rihanna)",
                    "PRIDE.",
                    "HUMBLE.",
                    "LUST.",
                    "LOVE. (feat. Zacari)",
                    "XXX. (feat. U2)",
                    "FEAR.",
                    "GOD.",
                    "DUCKWORTH."
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-red',
                'category' => 'hiphop',
            ],
            [
                'id' => '5685c958-56e9-4e24-9f7f-abf86491a2e0',
                'sku' => 'SKU-ASTROWORLD',
                'name' => 'Astroworld Travis Scott',
                'brand' => 'Travis Scott',
                'description' => 'Album ASTROWORLD - Travis Scott. Pengalaman psychedelic-trap yang luar biasa megah, dinamai berdasarkan taman bermain legendaris di Houston.',
                'price' => 700000,
                'image' => 'nooisefoto/travis.jpg',
                'tracklist' => json_encode([
                    "STARGAZING",
                    "CAROUSEL",
                    "SICKO MODE",
                    "R.I.P. SCREW",
                    "STOP TRYING TO BE GOD",
                    "NO BYSTANDERS",
                    "SKELETONS",
                    "WAKE UP",
                    "5% TINT",
                    "NC-17",
                    "ASTROTHUNDER",
                    "YOSEMITE",
                    "CAN'T SAY",
                    "WHO? WHAT!",
                    "BUTTERFLY EFFECT",
                    "HOUSTONFORNICATION",
                    "COFFEE BEAN"
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-red',
                'category' => 'hiphop',
            ],
            [
                'id' => 'f5a06bdb-d254-45f3-99c5-722872ed150c',
                'sku' => 'SKU-AMERICAN-DREAM',
                'name' => 'American Dream 21 Savage',
                'brand' => '21 Savage',
                'description' => 'Album American Dream - 21 Savage. Proyek hip-hop naratif mendalam yang menyuarakan perjalanan imigrasi 21 Savage dan realita keras meraih impian Amerika.',
                'price' => 550000,
                'image' => 'nooisefoto/american dream - 21 Savage.jpg',
                'tracklist' => json_encode([
                    "american dream",
                    "all of me",
                    "redrum",
                    "sneaky",
                    "pop ur shit",
                    "letter to my brudda",
                    "dangerous",
                    "née-nah (with Travis Scott & Metro Boomin)",
                    "see the real",
                    "prove it",
                    "should've wore a condom",
                    "just like me",
                    "red sky",
                    "dark days"
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-red',
                'category' => 'hiphop',
            ],
            [
                'id' => '4149aa8b-3b27-4d85-b09d-fba26c0fdf35',
                'sku' => 'SKU-WE-STILL-DONT-TRUST-YOU',
                'name' => "We Still Don't Trust You Metro Boomin Future",
                'brand' => 'Metro Boomin',
                'description' => "Album We Still Don't Trust You - Metro Boomin Future. Kolaborasi trap dan hip-hop megah penutup saga permusuhan paling dibicarakan di era rap modern.",
                'price' => 650000,
                'image' => 'nooisefoto/WE STILL DONT TRUST YOU.jpg',
                'tracklist' => json_encode([
                    "We Still Don't Trust You",
                    "Drink N Dance",
                    "Out Of My Hands",
                    "Jealous",
                    "This Sunday",
                    "Luv Bad Bitches",
                    "Amazing (Interlude)",
                    "All to Myself",
                    "Nights Like This",
                    "Came to the Party",
                    "Right 4 You",
                    "Mile High Memories",
                    "Red Leather"
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-white',
                'category' => 'hiphop',
            ],
            [
                'id' => '719de212-3cd2-4a79-a014-6a802f626104',
                'sku' => 'SKU-HOUSE-OF-BALLOONS',
                'name' => 'House of Ballons The Weeknd',
                'brand' => 'The Weeknd',
                'description' => 'Album House of Ballons - The Weeknd. Mixtape R&B alternatif legendaris yang meluncurkan karir global The Weeknd, terkenal dengan ketukan gelap dan atmosfer pesta malam yang liar.',
                'price' => 500000,
                'image' => 'nooisefoto/House of balloons - The Weeknd.jpg',
                'tracklist' => json_encode([
                    "High for This",
                    "What You Need",
                    "House of Balloons / Glass Table Girls",
                    "The Morning",
                    "Wicked Games",
                    "The Party & The After Party",
                    "Coming Down",
                    "Loft Music",
                    "The Knowing"
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-white',
                'category' => 'pop',
            ],
            [
                'id' => 'c39e067c-06c8-4e50-a229-069a671933bc',
                'sku' => 'SKU-WASTELAND',
                'name' => 'Wasteland Brent Faiyaz',
                'brand' => 'Brent Faiyaz',
                'description' => 'Album Wasteland - Brent Faiyaz. Sebuah album neo-R&B konseptual yang memadukan kisah drama kehidupan beracun, kehamilan, ketenaran, dengan melodi vokal sutera Brent.',
                'price' => 600000,
                'image' => 'nooisefoto/wasteland.jpg',
                'tracklist' => json_encode([
                    "VILLAIN'S THEME",
                    "LOOSE CHANGE",
                    "GRAVITY (feat. Tyler, The Creator)",
                    "HEAL YOUR HEART (INTERLUDE)",
                    "SKIT: EGOMANIAC",
                    "ALL MINE",
                    "PRICE OF FAME",
                    "GEYTOUT",
                    "WASTELAND",
                    "ROLLING STONE",
                    "DEAD MAN WALKING",
                    "ADDICTION",
                    "ROLE MODEL"
                ]),
                'color' => 'brown',
                'vinyl_class' => 'vinyl-red',
                'category' => 'rnb',
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->updateOrInsert(
                ['sku' => $product['sku']],
                [
                    'id' => $product['id'],
                    'name' => $product['name'],
                    'brand' => $product['brand'],
                    'description' => $product['description'],
                    'price' => $product['price'],
                    'image' => $product['image'],
                    'tracklist' => $product['tracklist'],
                    'color' => $product['color'],
                    'vinyl_class' => $product['vinyl_class'],
                    'category' => $product['category'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
